ALTER TABLE coin_type
    ADD COLUMN IF NOT EXISTS canonical_name TEXT,
    ADD COLUMN IF NOT EXISTS image_url_rev TEXT,
    ADD COLUMN IF NOT EXISTS metal TEXT,
    ADD COLUMN IF NOT EXISTS mass NUMERIC,
    ADD COLUMN IF NOT EXISTS diameter NUMERIC,
    ADD COLUMN IF NOT EXISTS mintage BIGINT,
    ADD COLUMN IF NOT EXISTS quality TEXT;
